import = [
    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
]
live_config_reload = false

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "Always"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 0.95
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 5
y = 5
