name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Install
        shell: bash
        run: |
          scripts/install.sh local-install

  build-and-test-cpp-aarch64:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install cross compiler and emulator
        run: |
          scripts/install.sh local-install

  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
