name: Macos Workflow

on:
  push:
    branches:
      - release*
    tags:
      - v*
      - nightly

  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'macos') || github.event_name == 'push'

    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run install_macos script
        run: |
          ./scripts/install_macos.sh
        shell: bash
