name: Nightly Tag Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜触发
  workflow_dispatch:  # 手动触发工作流

jobs:
  update-nightly-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 确保我们能够访问所有提交历史

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all tags and branches
        run: |
          git fetch --all

      - name: Check if nightly tag is on the latest main commit
        id: check_nightly
        run: |
          # Get the latest commit hash on the main branch
          MAIN_LATEST=$(git rev-parse origin/main)
          # Get the commit hash of the nightly tag, if it exists
          if git rev-parse nightly >/dev/null 2>&1; then
            NIGHTLY_COMMIT=$(git rev-parse nightly)
          else
            NIGHTLY_COMMIT=""
          fi
          # Compare the hashes
          if [ "$MAIN_LATEST" = "$NIGHTLY_COMMIT" ]; then
            echo "Nightly tag is already up-to-date with the latest main commit."
            echo "::set-output name=should_run::false"
          else
            echo "Nightly tag is not up-to-date with the latest main commit."
            echo "::set-output name=should_run::true"
          fi

      - name: Delete old nightly tag
        if: steps.check_nightly.outputs.should_run == 'true'
        run: |
          if git rev-parse nightly >/dev/null 2>&1; then
            git tag -d nightly
            git push origin :refs/tags/nightly
          else
            echo "No existing nightly tag found"
          fi

      - name: Create new nightly tag
        if: steps.check_nightly.outputs.should_run == 'true'
        run: |
          git tag nightly
          git push origin nightly
